[project]
name = "multicast-local"
authors = ["MultiChain Developer Team"]
description = "A blockchain-based local multicast management system"
telemetry = false
requirements = []
[contracts.multicast-local-manager]
path = "contracts/multicast-local-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
